name: Backend Install

description: 'Installs required dependencies for backend'

runs:
  using: composite

  steps:
    - name: CDK Dependencies
      id: cdk-cache
      uses: actions/cache@v3
      with:
        path: backend/node_modules
        key: backend-${{ hashFiles('backend/package-lock.json') }}

    - name: Install Backend
      if: steps.cdk-cache.outputs.cache-hit != 'true'
      run: npm ci
      working-directory: backend
      shell: bash

    - name: Install Backend Sources
      run: npm run cinstall-backend
      working-directory: backend
      shell: bash
