name: Backend Install

description: 'Installs required dependencies for backend'

runs:
  using: composite
  steps:
    - name: CDK Dependencies
      id: cdk-cache
      uses: actions/cache@v3
      with:
        path: backend/node_modules
        key: backend-${{ hashFiles('backend/package-lock.json') }}

    - name: Install Backend
      if: steps.cdk-cache.outputs.cache-hit != 'true'
      run: npm ci
      working-directory: backend
      shell: bash

    - name: Install Backend Sources
      run: npm run cinstall-backend
      working-directory: backend
      shell: bash

    - name: Create backend/.env file
      run: |
        touch .env
        echo SENDER_EMAIL=test@test.com >> .env
        echo CERTIFICATE_ARN=${{ secrets.CERTIFICATE_ARN_PROD }} >> .env
      working-directory: backend
      shell: bash
