name: Frontend Install

description: 'Installs required dependencies for frontend'

runs:
  using: composite
  steps:
    - name: CDK Dependencies
      id: cdk-cache
      uses: actions/cache@v3
      with:
        path: backend/node_modules
        key: backend-${{ hashFiles('backend/package-lock.json') }}

    - name: Install CDK
      if: steps.cdk-cache.outputs.cache-hit != 'true'
      run: npm ci
      working-directory: backend
      shell: bash

    - name: Frontend Dependencies
      id: frontend-cache
      uses: actions/cache@v3
      with:
        path: frontend/node_modules
        key: frontend-${{ hashFiles('frontend/package-lock.json') }}

    - name: Install Frontend Dependencies
      if: steps.frontend-cache.outputs.cache-hit != 'true'
      run: npm run cinstall-frontend
      working-directory: backend

    - name: Create frontend/src/aws-exports.js file
      run: |
        touch aws-exports.js
        echo const awsmobile = { aws_project_region: \'${{ secrets.CDK_DEFAULT_REGION }}\', aws_cognito_region: \'${{ secrets.CDK_DEFAULT_REGION }}\', aws_user_pools_id: \'${{secrets.COGNITO_USERPOOL_ID_PROD}}\', aws_user_pools_web_client_id: \'${{ secrets.COGNITO_WEB_CLIENT_ID_PROD }}\', mandatorySignIn: true, aws_appsync_graphqlEndpoint: \'${{ secrets.GRAPHQL_ENDPOINT_PROD }}\', aws_appsync_region: \'${{ secrets.CDK_DEFAULT_REGION }}\', aws_appsync_authenticationType: \'AMAZON_COGNITO_USER_POOLS\' } >> aws-exports.js
        echo export default awsmobile >> aws-exports.js
        cat aws-exports.js
      working-directory: frontend/src
