name: deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    permissions:
      actions: write
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Backend and Sources
        uses: ./.github/actions/backend

      - name: Create backend/.env file
        run: |
          touch .env
          echo SENDER_EMAIL=${{ secrets.SENDER_EMAIL }} >> .env
          echo CERTIFICATE_ARN=${{ secrets.CERTIFICATE_ARN_PROD }} >> .env
        working-directory: backend

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_SERVICE_ROLE_PROD }}
          aws-region: ${{ secrets.CDK_DEFAULT_REGION }}

      - name: CDK Deploy Backend
        run: npm run deploy-backend prod
        env:
          CERTIFICATE_ARN: ${{secrets.CERTIFICATE_ARN_PROD}}
          SENDER_EMAIL: ${{secrets.SENDER_EMAIL}}
        working-directory: backend

  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    needs: deploy-backend
    permissions:
      actions: write
      contents: read
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Frontend
        uses: ./.github/actions/frontend

      - name: Create frontend/src/aws-exports.js file
        run: |
          touch aws-exports.js
          echo const awsmobile = { aws_project_region: \'${{ secrets.CDK_DEFAULT_REGION }}\', aws_cognito_region: \'${{ secrets.CDK_DEFAULT_REGION }}\', aws_user_pools_id: \'${{secrets.COGNITO_USERPOOL_ID_PROD}}\', aws_user_pools_web_client_id: \'${{ secrets.COGNITO_WEB_CLIENT_ID_PROD }}\', mandatorySignIn: true, aws_appsync_graphqlEndpoint: \'${{ secrets.GRAPHQL_ENDPOINT_PROD }}\', aws_appsync_region: \'${{ secrets.CDK_DEFAULT_REGION }}\', aws_appsync_authenticationType: \'AMAZON_COGNITO_USER_POOLS\' } >> aws-exports.js
          echo export default awsmobile >> aws-exports.js
          cat aws-exports.js
        working-directory: frontend/src

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_SERVICE_ROLE_PROD }}
          aws-region: us-east-1

      - name: Build Frontend
        run: npm run build-frontend
        working-directory: backend

      - name: CDK Deploy Frontend
        run: npm run deploy-frontend prod
        env:
          CERTIFICATE_ARN: ${{secrets.CERTIFICATE_ARN_PROD}}
        working-directory: backend
